from typing import Any


def _quote_identifier(identifier: str) -> str:
    """
    Quote a PostgreSQL identifier safely.

    Example:
        users -> "users"
        user_name -> "user_name"
    """
    if not identifier:
        raise ValueError("Identifier cannot be empty")

    escaped = identifier.replace('"', '""')
    return f'"{escaped}"'


def _format_column(column: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    """
    Convert one analyzed column into a PostgreSQL column definition.

    Returns:
        (SQL fragment, transformation record)
    """

    name = column.get("name")
    source_type = column.get("source_type")
    target_type = column.get("target_type")
    migration_rule = column.get("migration_rule")

    if not name:
        raise ValueError("Column name cannot be empty")

    if not target_type:
        raise ValueError(
            f"Unsupported datatype for column '{name}': {source_type}"
        )

    column_sql = (
        f"{_quote_identifier(name)} "
        f"{target_type}"
    )

    if column.get("auto_increment"):
     column_sql += " GENERATED BY DEFAULT AS IDENTITY"

    if column.get("nullable") is False:
      column_sql += " NOT NULL"

    default = column.get("default")
    if default is not None:
      column_sql += f" DEFAULT {default}"

    transformation = {
        "type": "DATATYPE_MAPPING",
        "table": None,
        "column": name,
        "source": source_type,
        "target": target_type,
        "rule": migration_rule,
    }

    return column_sql, transformation


def _generate_primary_key(
    primary_keys: list[str],
) -> str | None:
    """
    Generate a PostgreSQL PRIMARY KEY constraint.
    """

    if not primary_keys:
        return None

    columns = ", ".join(
        _quote_identifier(column)
        for column in primary_keys
    )

    return f"PRIMARY KEY ({columns})"


def _generate_unique_constraints(
    constraints: list[dict[str, Any]],
) -> list[str]:
    """
    Generate UNIQUE constraints represented in the canonical schema.
    """

    statements = []

    for constraint in constraints:
        if constraint.get("type") != "UNIQUE":
            continue

        column = constraint.get("column")

        if not column:
            continue

        statements.append(
            f"UNIQUE ({_quote_identifier(column)})"
        )

    return statements

def _generate_check_constraints(
    constraints: list[dict[str, Any]]
) -> list[str]:
    statements = []

    for constraint in constraints:
        if constraint.get("type") != "CHECK":
            continue

        condition = constraint.get("condition")
        if not condition:
            continue

        constraint_name = constraint.get("name")

        if constraint_name:
            statements.append(
                f'CONSTRAINT {_quote_identifier(constraint_name)} CHECK ({condition})'
            )
        else:
            statements.append(
                f'CHECK ({condition})'
            )

    return statements

def _generate_foreign_keys(
    foreign_keys: list[dict[str, Any]],
) -> list[str]:
    """
    Generate FOREIGN KEY constraints.
    """

    statements = []

    for foreign_key in foreign_keys:
        column = foreign_key.get("column")
        references_table = foreign_key.get("references_table")
        references_column = foreign_key.get("references_column")

        if not column or not references_table or not references_column:
            continue

        statements.append(
            "FOREIGN KEY "
            f"({_quote_identifier(column)}) "
            "REFERENCES "
            f"{_quote_identifier(references_table)}"
            f"({_quote_identifier(references_column)})"
        )

    return statements


def _generate_indexes(
    indexes: list[dict[str, Any]],
) -> list[str]:
    """
    Generate PostgreSQL CREATE INDEX statements.
    """

    statements = []

    for index in indexes:
        name = index.get("name")
        columns = index.get("columns", [])
        unique = index.get("unique", False)
        primary = index.get("primary", False)

        if not name or not columns:
            continue

        # PRIMARY indexes are represented by PRIMARY KEY
        # and should not be generated separately.
        if primary:
            continue

        index_columns = ", ".join(
            _quote_identifier(column)
            for column in columns
        )

        unique_keyword = "UNIQUE " if unique else ""

        statements.append(
            f"CREATE {unique_keyword}INDEX "
            f"{_quote_identifier(name)} "
            f"ON "
            f"{{table_name}}"
            f"({index_columns});"
        )

    return statements

def _generate_on_update_triggers(
    table_name: str,
    columns: list[dict[str, Any]],
) -> list[str]:
    """
    Generate PostgreSQL trigger function and trigger statements
    for MySQL ON UPDATE column behavior.
    """

    on_update_columns = [
        column
        for column in columns
        if column.get("on_update")
    ]

    if not on_update_columns:
        return []

    function_name = f"{table_name}_set_on_update"

    assignments = []

    for column in on_update_columns:
        column_name = column.get("name")

        if not column_name:
            continue

        assignments.append(
            f"    NEW.{_quote_identifier(column_name)} = CURRENT_TIMESTAMP;"
        )

    if not assignments:
        return []

    function_sql = (
        f"CREATE OR REPLACE FUNCTION "
        f"{_quote_identifier(function_name)}()\n"
        "RETURNS TRIGGER AS $$\n"
        "BEGIN\n"
        + "\n".join(assignments)
        + "\n"
        "    RETURN NEW;\n"
        "END;\n"
        "$$ LANGUAGE plpgsql;"
    )

    trigger_sql = (
        f"CREATE TRIGGER "
        f"{_quote_identifier(function_name + '_trigger')}\n"
        f"BEFORE UPDATE ON {_quote_identifier(table_name)}\n"
        "FOR EACH ROW\n"
        f"EXECUTE FUNCTION {_quote_identifier(function_name)}();"
    )

    return [
        function_sql,
        trigger_sql,
    ]


def generate_postgresql_sql(schema: dict[str, Any]) -> dict[str, Any]:
    """
    Generate PostgreSQL migration SQL from the analyzed
    canonical schema.

    Expected input:

        analyze_schema(sql)

    Output:

        {
            "target_database": "postgresql",
            "sql": "...",
            "transformations": [...],
            "warnings": [...]
        }
    """

    if not isinstance(schema, dict):
        raise TypeError("Schema must be a dictionary")

    tables = schema.get("tables", [])

    if not isinstance(tables, list):
        raise ValueError("Schema 'tables' must be a list")

    sql_statements: list[str] = []
    transformations: list[dict[str, Any]] = []
    warnings: list[dict[str, Any]] = []

    for table in tables:
        table_name = table.get("name")

        if not table_name:
            warnings.append({
                "type": "INVALID_TABLE",
                "message": "Skipped table because table name is missing.",
            })
            continue

        columns = table.get("columns", [])

        if not columns:
            warnings.append({
                "type": "EMPTY_TABLE",
                "table": table_name,
                "message": "Table has no columns and was skipped.",
            })
            continue

        table_definitions: list[str] = []

        # -------------------------------------------------
        # Columns
        # -------------------------------------------------

        for column in columns:
            try:
                column_sql, transformation = _format_column(column)

                transformation["table"] = table_name

                table_definitions.append(column_sql)
                transformations.append(transformation)

            except ValueError as exc:
                warnings.append({
                    "type": "UNSUPPORTED_COLUMN",
                    "table": table_name,
                    "column": column.get("name"),
                    "message": str(exc),
                })

        # -------------------------------------------------
        # Primary Key
        # -------------------------------------------------

        primary_key = _generate_primary_key(
            table.get("primary_keys", [])
        )

        if primary_key:
            table_definitions.append(primary_key)

            transformations.append({
                "type": "PRIMARY_KEY",
                "table": table_name,
                "columns": table.get("primary_keys", []),
                "action": "PRESERVED",
            })

        # -------------------------------------------------
        # UNIQUE constraints
        # -------------------------------------------------

        unique_constraints = _generate_unique_constraints(
            table.get("constraints", [])
        )

        for constraint in unique_constraints:
            table_definitions.append(constraint)

            transformations.append({
                "type": "UNIQUE_CONSTRAINT",
                "table": table_name,
                "action": "PRESERVED",
            })
        check_constraints = _generate_check_constraints(
                table.get("constraints", [])
            )
        for constraint in check_constraints:
            table_definitions.append(constraint)

            transformations.append({
                "type": "CHECK_CONSTRAINT",
                "table": table_name,
                "action": "PRESERVED",
            })

        # -------------------------------------------------
        # FOREIGN KEY constraints
        # -------------------------------------------------

        foreign_keys = _generate_foreign_keys(
            table.get("foreign_keys", [])
        )

        for foreign_key in foreign_keys:
            table_definitions.append(foreign_key)

            transformations.append({
                "type": "FOREIGN_KEY",
                "table": table_name,
                "action": "PRESERVED",
            })

        # -------------------------------------------------
        # CREATE TABLE
        # -------------------------------------------------

        if table_definitions:
            create_table_sql = (
                f"CREATE TABLE {_quote_identifier(table_name)} (\n"
                + ",\n".join(
                    f"    {definition}"
                    for definition in table_definitions
                )
                + "\n);"
            )

            sql_statements.append(create_table_sql)

        # -------------------------------------------------
        # INDEXES
        # -------------------------------------------------

        index_statements = _generate_indexes(
            table.get("indexes", [])
        )

        for index_statement in index_statements:
            index_statement = index_statement.replace(
                "{table_name}",
                _quote_identifier(table_name),
            )

            sql_statements.append(index_statement)

            transformations.append({
                "type": "INDEX",
                "table": table_name,
                "action": "PRESERVED",
            })

        # -------------------------------------------------
        # ON UPDATE triggers
        # ------------------------------------------------- 

        on_update_statements = _generate_on_update_triggers(
            table_name,
            columns,
        )

        for on_update_statement in on_update_statements:
            sql_statements.append(on_update_statement)

        if on_update_statements:
            transformations.append({
                "type": "ON_UPDATE_TRIGGER",
                "table": table_name,
                "action": "CONVERTED_TO_POSTGRESQL_TRIGGER",
            })

        # -------------------------------------------------
        # Unsupported features
        # -------------------------------------------------

        for feature in table.get("unsupported_features", []):
            warnings.append({
                "type": "UNSUPPORTED_FEATURE",
                "table": table_name,
                "feature": feature.get("type"),
                "name": feature.get("name"),
                "message": (
                    "Feature was detected by the schema parser "
                    "but was not generated in PostgreSQL SQL."
                ),
            })

        # -------------------------------------------------
        # Triggers
        # -------------------------------------------------

        for trigger in table.get("triggers", []):
            warnings.append({
                "type": "TRIGGER_NOT_GENERATED",
                "table": table_name,
                "trigger": trigger.get("name"),
                "message": (
                    "MySQL trigger was detected but trigger SQL "
                    "generation is not implemented yet."
                ),
            })

    return {
        "target_database": "postgresql",
        "sql": "\n\n".join(sql_statements),
        "transformations": transformations,
        "warnings": warnings,
    }