services:
  postgres:
    image: postgres:17
    container_name: pivot-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pivot_password
      POSTGRES_DB: pivot_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: