"""create migration runs table

Revision ID: 7886c2310ca9
Revises: 5ed9d84e3aa3
Create Date: 2026-10-04 11:28:44.830231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7886c2310ca9'
down_revision: Union[str, Sequence[str], None] = '5ed9d84e3aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_sql', sa.Text(), nullable=False),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('migration_result', sa.JSON(), nullable=True),
    sa.Column('ml_prediction', sa.JSON(), nullable=True),
    sa.Column('ai_review', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_runs_id'), 'migration_runs', ['id'], unique=False)
    op.create_index(op.f('ix_migration_runs_project_id'), 'migration_runs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_migration_runs_project_id'), table_name='migration_runs')
    op.drop_index(op.f('ix_migration_runs_id'), table_name='migration_runs')
    op.drop_table('migration_runs')
    # ### end Alembic commands ###
